language: 'php'
php:
- '7.2'

cache:
  directories:
  - 'vendor'

before_install:
- phpenv config-rm xdebug.ini || return 0 # Disable Xdebug

install:
- composer install

before_script:
- phpenv config-rm xdebug.ini || return 0 # Disable Xdebug

jobs:
  include:
  - stage: 'Code analysis'
    name: 'Lint code using PHP-CS-Fixer'
    script:
    - composer app:lint-php-cs-fixer

  - stage: 'Code analysis'
    name: 'Analyze code using PHPStan'
    script:
    - composer app:analyze-phpstan
